# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bf82ef93be9ecd2db65690dac4e084d2c0df1dbe2edb4f46f01224ff17eabd7f149c3d512c85ca845c7e06358b77036b1f501131814d9abb768bdcd55a73ffb

test:
  secret_key_base: bc1891d67daba294f426f24168135992a4bc1d11a1f1f6708a244805f9e92d2b2650a135d8765012f46813dc940cf31170d796a9efccef81742829fb1d3d4864

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
